### PR TITLE
Use ICE's autocomplete function

### PR DESCRIPTION
**Pull request by John128217**
Hi Marco, I really love your work!  Thank you for sharing your workflow!

However, your script automatically fills the sky with black and it is visually unpleasing.  There is an auto complete function in ICE but it cannot be used with normal orientation since it can only fills a tiny part on the top.  

In this pull request, I declared that in ICE, the user should change the pitch of the photo to 90 degrees so that the giant hole is in the middle.  ICE's auto completion can handle that pretty well.  Of course, I changed the settings in "create tif cube faces" step so the end product looks normal.

### CODE REVIEW

**Comment by sinky** [comment]
Hi John,
this is a really nice idea to enhance the panorama.

My problem with changing the pitch of the equirectangular pano is that it is also used to create small previews and a lower resolution fallback for mobile devices. Which after changing the pitch now looks unpleasing. If there was one program which could change the pitch afterwards ...

So right now you would have to create two files from ICE. One for the previews and one for the cube faces.

I will think about this.

**Comment by John128217** [comment]
Hi Marco,

Issue fixed. Previews will now get displayed correctly.

After several testing, I found I can fix the orientation of the pano by using nona.exe.
You just need to change the second line of .pto file to `p E0 R0 f2 h2048 n"TIFF_m" u0 v360 w4096`.

I removed the ratio expanding part because ICE's autocomplete will take care of the ratio.

I also made the program remove all the temporary files created during the execution (pano.pto) so the folder will look tidier.

**Comment by sinky** [comment]
Cool didn't know that nona can do that. I would like to archive the full resolution equirectangular in the "right" orientation.

So my idea is to first fix the orientation of the pano created by ICE and then use this as before to create the previews and cube faces. For me this looks like a "cleaner" way.

```
# Created by Panotools::Script 0.28

p E0 R0 f2 h10240 n"JPEG_m" u0 v360 w20480
m g1 i0 m2 p0.00784314

# Image lines
i a0 b0 c0 d0 e0 f4 h10240 n"pano.jpg" p90 r0 v360 w20480 y0

# Variable lines
[...]
```

Also i noticed that we can use "JPEG_m" as output format. So there is no need to convert the tif to jpg.

**Comment by sinky** [comment]
Hi,
with my changes the script works with uncomplete panos by adding black on top.
If already 2:1 ratio no changes are made.
And you can fix the pitch by adding the -fixPitch switch.

The original file doesn't need to be in the working dir anymore.

**Pull request merged**
